name: Divinely Creative
favicon: null
layout_spectrum: 0.6729705617763102
typography_spectrum: 0.20315383188426495
title: Divinely Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-000000-11
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1695915348827839
  lightness: 0.9049429160077125
  saturation: 0.9746795573737472
  rhythmicContrast: 0.4047099801246077
purpose: []
