name: Divinely Creative
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06984
title: Divinely Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75408146-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#626262'
    - '#909090'
    - '#3e3e3e'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
